evaluate-variables: true
external-checks-dir:
  - custom_checkov_policies
file:
  - tfplan.json
framework:
  - all
summary-position: top
skip-check:
  - CKV_AWS_18  # s3 access logging
check:
  - CUS_AWS_1   # tagging
  - CKV_AWS_7   # key rotation